papermoonio/moonbeam-docs-test-suite

- test/builders/build/eth-api/libraries/web3py/test_deploy_contract.py
install fixed solc version (0.8.19) before using it
> install fixed solc version (0.8.19) before using it

- package-lock.json
- package.json
- test/builders/build/eth-api/libraries/web3js/deploy-contract.js
- test/builders/build/eth-api/libraries/web3js/send-transaction.js
This PR updates the Web3.js tests 🥳 🎉
> update web3js tests for v4

- test/builders/build/eth-api/libraries/ethers/deploy-contract.js
This PR hopes to fix the issue with the docs testing suite, where we would get the following error while running the deploy contract Ethers tests: `Error: nonce has already been used`
It fixes it by retrieving the initial nonce before any of the deploy contract Ethers tests are run and then manually incrementing the nonce for each transaction, so each transaction has its own dedicated nonce and there will be no overlap.
I couldn't replicate the issue locally, so I'm not sure if this will work, but I think in theory it makes sense.
> explicitly set the nonce for the ethers tests

- package-lock.json
- package.json
- test/builders/get-started/eth-compare/account-balances.js
This adds tests for the snippets on the [Account Balances](https://docs.moonbeam.network/builders/get-started/eth-compare/balances/) page of the docs
> add tests for the account balances page

- package-lock.json
- package.json
- test/builders/interoperability/xcm/xc20/overview/retrieve-xc20s.js
The number of XC-20s deployed to Moonbeam has increased due to the xcPINK proposal passing
Docs PRS:
- https://github.com/moonbeam-foundation/moonbeam-docs/pull/839
- https://github.com/moonbeam-foundation/moonbeam-docs-cn/pull/394
> update number of xc-20s on moonbeam to include xcPINK

- package-lock.json
- package.json
- test/builders/build/eth-api/dev-env/hardhat/package-lock.json
- test/builders/build/eth-api/dev-env/hardhat/package.json
- test/builders/build/runtime-upgrades.js
- test/builders/interoperability/xcm/xc20/overview/retrieve-xc20s.js
This PR bumps Moonbeam to Runtime 2700 and updates the XC-20 count to 38 to account for xcBNCS
> Update runtime version and xc-20 count for Moonbeam

- package-lock.json
- package.json
- test/builders/build/runtime-upgrades.js
update tests for runtime 2801 on moonriver and install latest dependencies
> update tests for runtime 2801 on moonriver

- package-lock.json
- package.json
- requirements.txt
- test/builders/build/runtime-upgrades.js
- test/builders/interoperability/xcm/xc20/overview/retrieve-xc20s.js
xcTNKR was added as a new XC-20 on Moonriver and runtime 2801 was released on Moonbeam
> Bump moonbeam to runtime 2801 and update moonriver xc-20 numbers

- package-lock.json
- package.json
- test/builders/build/eth-api/dev-env/hardhat/package-lock.json
- test/builders/build/eth-api/dev-env/hardhat/package.json
- test/builders/build/runtime-upgrades.js
Update tests as moonbase alpha is now on rt 2902
Original PR: https://github.com/moonbeam-foundation/moonbeam-docs/pull/909
> update moonbase to 2902

- package-lock.json
- package.json
- test/builders/interoperability/xcm/xc20/overview/retrieve-xc20s.js
update xc20 count to account for xcSTINK on Moonbeam
> update xc20 count on moonbeam

- package-lock.json
- package.json
- test/builders/build/eth-api/dev-env/hardhat/package-lock.json
- test/builders/build/eth-api/dev-env/hardhat/package.json
- test/builders/build/runtime-upgrades.js
update packages to the latest versions and bump moonbase to runtime 3000
> bump moonbase to runtime 3000

- package-lock.json
- package.json
- test/builders/build/runtime-upgrades.js
This PR updates the runtime upgrades test for Moonbeam now that it's been upgraded to 3001. It also updates the latest packages
> update moonbeam for runtime 3001

- test/builders/build/runtime-upgrades.js
updates moonriver spec version in test suite to 3100
> updates moonriver spec version to 3100

- test/builders/build/runtime-upgrades.js
Updates Moonbeam spec version to 3100 for testing
> updates moonbeam runtime to 3100

- package-lock.json
- package.json
- test/builders/interoperability/xcm/xc20/overview/retrieve-xc20s.js
This PR bumps the dependencies and the number of XC-20s on Moonbeam
> bump xc-20s on moonbeam to 47

- test/builders/build/runtime-upgrades.js
Forgot to save the file with the modification 😬
> Moonbase to RT3300 Round 2

- test/builders/build/runtime-upgrades.js
Updates runtime 3200 for Moonbeam
> update runtime 3200 for Moonbeam

- test/builders/build/runtime-upgrades.js
> Moonriver to 3300

- test/builders/build/runtime-upgrades.js
> Runtime Upgrade MB 3300

- test/builders/build/eth-api/dev-env/hardhat/package.json
- test/builders/build/runtime-upgrades.js
Changed the runtime-upgrades.js file to have the latest runtime version in Moonbase Alpha
> Runtime Upgrade MBA 3400

- test/builders/build/runtime-upgrades.js
update runtime 3400 for Moonriver
> update runtime 3400 for Moonriver

- test/builders/get-started/eth-compare/consensus-finality/ethereum-libraries/ethers.js
- test/builders/get-started/eth-compare/consensus-finality/ethereum-libraries/web3.js
Update Consensus and Finality tests.
These have been tested locally and are passing.
> fix finality tests

- test/builders/build/runtime-upgrades.js
Changed assertion for Moonbeam Runtime 3400
> Moonbeam Runtime 3400

- test/builders/build/runtime-upgrades.js
Changed assertion for Runtime 3500 for MBA and 3401 for MR
> Runtime 3500 for MBA and 3401 for MR

- test/builders/build/runtime-upgrades.js
updated assertion of MBA to Runtime 3501
> updated assertion of MBA to Runtime 3501

- test/builders/build/runtime-upgrades.js
updated assertion of MB to Runtime 3401
> updated assertion of MB to Runtime 3401

- test/builders/build/runtime-upgrades.js
updated assertion of MBA to runtime 3600
> Updated assertion of MBA to runtime 3600

- test/builders/build/runtime-upgrades.js
updated runtime 3600 for Moonriver
> updated runtime 3600 for Moonriver

- test/builders/build/runtime-upgrades.js
> Updated Moonbeam to RT3600

- test/builders/build/runtime-upgrades.js
Updating Moonbase to runtime 3700
> Updating Moonbase to runtime 3700

- test/builders/build/eth-api/libraries/ethers/send-transaction.js
Should fix... tests ran fine locally   
53 passing (2m)
> Fix Test Suite Bug

- test/builders/build/eth-api/libraries/ethers/send-transaction.js
> Test Suite Fix

- test/builders/build/runtime-upgrades.js
> Moonbase 3702

- package.json
This pull request adds a new dependency to the project. The most important change is the inclusion of the `bip39` package in the `package.json` file, which will allow for mnemonic phrase generation and validation in the codebase.
Dependency management:
* Added the `bip39` package (version ^3.1.0) to the list of dependencies in `package.json`, enabling support for mnemonic phrase operations.
> Add Bip39 to Package.json
